# Generated by Django 4.2.21 on 2025-05-19 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30)),
                ("order", models.PositiveSmallIntegerField()),
                ("money", models.IntegerField(default=1500)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_turn", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "order")},
            },
        ),
    ]
